#+TITLE: Book Reading Combo #1
#+SETUPFILE: theme.setup
#+INCLUDE: ./nav.org

* #Combo in Combo#
** 码农: 进击的 Java
- 码农; 图灵社区. 码农·进击的Java（总第16期） (Kindle Location 21). 人民邮电出版社. Kindle Edition.
- 一个不错的点: 读源码不要一行一行读, 要带着目标, 追主线.
** 科技之巅 《麻省理工科技评论》50大全球突破性技术深度剖析
- tzx: 感觉太空, 电池, 基因, AI 是热点
- 原来除了 SpaceX, Jeff Bezos 也有一个太空相关的公司, 叫 Blue Origin, 而且比 SpaceX 提前成功发射可以降落的火箭
- Slack 是一种智能沟通机器人
- 虚拟现实, 自动驾驶, 车对车通信 (V2V communication), 基因工程, 太阳能, 风能
- 在“ 液体 活 检”（ liquid biopsy）
- 支付, apple pay
- Microscale 3- D Printing 微型 3D 打印
- Mobile Collaboration 移动协作: quip
- blue ocean
- Neuromorphic Chips 神经 形态 芯片
- Agricultural Drones 农用 无 人机
- Prenatal DNA Sequencing 产前 DNA 测 序
- Supergrids 超级 电网
- Light- Field Photography 光 场 摄影 术
- High-Speed Materials Discovery 高速筛选电池材料
* 金字塔原理
** 中文版序
{{{begin-summary}}}
《金字塔原理》介绍了一种能清晰地展现思路的有效方法。掌握了金字塔原理，
就能重点突出，逻辑清晰。不管是在政界、商界、学界，还是在企事业单位，所
有高、中、基层职场人士，只要你需要思考和沟通，就会从金字塔原理受益。金
字塔结构思考力是领导力的必要素质，本书是训练思考、使表达呈现逻辑性的实
用宝典。

金字塔原理的基本概念:

- 金字塔原理是一种重点突出、逻辑清晰、层次分明、简单易懂的思考方式、沟通方式、规范动作。
- 金字塔原理的基本结构是：结论先行，以上统下，归类分组，逻辑递进。先重要后次要，先总结后具体，先框架后细节，先结论后原因，先结果后过程，先论点后论据。
- 金字塔原理训练表达者：关注、挖掘受众的意图、需求点、利益点、关注点和兴趣点，想清说什么（内容），怎么说（思路、结构），掌握沟通的标准结构、规范动作。
- 金字塔能够达到的沟通效果：观点鲜明、重点突出、思路清晰、层次分明、简单易懂，让受众有兴趣，能理解，记得住。
- 搭建金字塔结构的具体做法是：自上而下表达，自下而上思考，纵向总结概括，横向归类分组，序言讲故事，标题提炼思想精华。
{{{end-summary}}}
{{{begin-fold(冯唐≪老聃的金字塔原则≫)}}}
https://book.douban.com/review/5555714/

进了麦肯锡公司，我被训练的第一个玩意儿是金字塔原则。后来证明，这也是之
后诸多训练中，最宝贵最有用的玩意儿。

对于金字塔每一层的支持论据，有个极高的要求：MECE（Mutually exclusive
and collectively exhaustive），即彼此相互独立不重叠，但是合在一起完全
穷尽不遗漏。不遗漏才能不误事，不重叠才能不做无用功。
{{{end-fold}}}
** 前言
1967 年还很少有人接受我的理论，但是麦肯锡公司的一些智者却慷慨地指出了
我的理论中存在的问题，帮助我改进。现在，金字塔原理已经成为麦肯锡公司的
标准，并被麦肯锡看做是其公司理念和规范的重要组成部分。

实际应用金字塔原理需要相当的毅力。但是，如果你有意地以书中介绍的方法强迫自己“先想后写”，你的写作能力肯定能够得到惊人的改善，使你能够：

- 缩短完成最终一稿通常所需的时间；
- 提高文章的条理性；
- 缩短文章的长度。最终的结果是，使你能够在最短的时间内写出简明扼要、思路清晰的文章。
** 第 1 篇 表达的逻辑
文章条理不清还有一个比上面提到的原因更常见、但也更容易改进的原因，即文
章的结构（structure）——也就是句子的组织顺序（不管句子本身写得是好是坏）。

金字塔结构中，思想之间的联系方式可以是纵向的（vertically）——即任何一个
层次上的思想都是对其下面一个层次上思想的总结；也可以是横向的
（horizontally）——即多个思想因共同组成同一个逻辑推理过程，而被并列排在一起。
*** 第 1 章 为什么要用金字塔结构
如果你的文章结构呈金字塔形，文章的思路自金字塔顶部开始逐渐向下展开，那
么读者肯定会觉得你的文章比较容易读懂。

- 你可以通过检查你的思想是否用金字塔结构相互关联，从而确定你是否正确地构建了文章的结构。 ::
    - 金字塔中的思想以 3 种方式互相关联——向上、向下和横向。位于一组思想的上一个层次的思想是对这一组思想的概括，这一组思想则是对其上一层次思想的解释和支持。
    - 文章中任一层次上的思想必须是对其下一层次思想的总结概括
    - 每组中的思想必须属于同一逻辑范畴
    - 每组中的思想必须按照逻辑顺序组织 \\
    组织思想基本上只可能有4种逻辑顺序：
    + 演绎顺序：大前提、小前提、结论
    + 时间（步骤）顺序：第一、第二、第三
    + 结构（空间）顺序：波士顿、纽约、华盛顿
    + 程度（重要性）顺序：最重要、次重要，等等
**** 归类分组，将思想组织成金字塔
- 逻辑关系
- 7
- 归类分组, 搭建金字塔
- 找出逻辑关系, 抽象概括
**** 自上而下表达，结论先行
**** 自下而上思考，总结概括
*** 第 2 章 金字塔内部的结构
金字塔中的子结构，能够加快你梳理思想的过程：
- 主题与子主题之间的纵向关系
- 各子主题之间的横向关系
- 序言的叙述方式
**** 纵向关系
- 这种表述之所以清晰，是因为其思想的组织一直紧紧围绕着回答由主题引发的读者的疑问。
- 金字塔结构的巨大价值就在于它迫使你在理清思路时，从视觉上使纵向的疑问／回答式对话关系清晰化。
**** 横向关系
- 演绎性思想组合是由几个承前启后的论述组成的。
- 归纳性思想组合中的思想互相关联，
**** 序言的结构
问题的起源和发展必然以叙述的形式出现，因此也应当按照典型的叙述模式发展。
序言的开头应向读者说明“背景”（situation）的时间和地点。
在这一背景中应当发生了某件事情，可称为“冲突”（complication），
使读者提出（或将使读者提出）你的文章将要“回答”（answer）的“疑问”（question）。
*** 第 3 章 如何构建金字塔
**** 自上而下法
自上而下法构建金字塔的步骤：
- 提出主题思想。
- 设想受众的主要疑问。
- 写序言：背景－冲突－疑问－回答。
- 与受众进行疑问/回答式对话。
- 对受众的新疑问，重复进行疑问/回答式对话。
**** 自下而上法
自下而上思考：
- 列出你想表达的所有思想要点。
- 找出各要点之间的逻辑关系。
- 得出结论。
**** 初学者注意事项
- 一定先搭结构，先尝试自上而下法
- 序言先写背景，将背景作为序言的起点
- 先多花时间思考序言，不要省略
- 将历史背景放在序言中
- 序言仅涉及读者不会对其真实性提出质疑的内容
- 在关键句层次上，更宜选择归纳推理法而非演绎论证法 (interesting)
*** 第 4 章 序言的具体写法
文章的序言（前言、引言、导言）概述读者已知的信息，并将这些信息与文章将
要回答的疑问建立联系，然后作者就可以将全部精力放在提供回答疑问的答案上。
如果是写文章，就是“序言”； *如果是演讲，就是“开场白”。*
**** 序言的讲故事结构
序言要用讲故事形式，是为了让读者抛开复杂的思想，专注于你的话题。激发读
者兴趣，吸引注意力：新奇、悬念、与读者本人相关。

序言必须采取“*背景—冲突—疑问—解决方案*”的结构，但是，各部分的顺序可以有所变化，以创造不同的文章风格。
基本结构:
- 背景（S, Situation）＝业务多元化研究服务在过去5年中增长了40％。
- 冲突（C, Complication）＝无法证明我们的工作对客户有明显益处。
- 疑问（Q, Question）＝如何确保多元化研究确实对客户有明显益处？
- 回答（A, Answer）＝实施“公司发展项目”，以研究该问题。
**** 序言的常见模式
你写文章的目的通常是回答以下 4 类问题之一：
- 我们应该做什么？
- 我们应该如何做（将如何做／是如何做的）？
- 我们是否应该这样做？
- 为什么会发生这种情况？

当然，你常用的文章模式取决于你工作的内容。下面我将逐个介绍在商务文章中最常见的 4 种模式：
- 发出指示式（针对“我们应该做什么”或“我们应该如何做”等问句）
- 请求支持式（针对“我们是否应该这样做”等问句）
- 解释做法式（针对“我们应该如何做”等问句）
- 比较选择式（针对“我们应该做什么”等问句）
**** 序言的常见模式——以咨询为例
*** 第 5 章 演绎推理与归纳推理 (easy)
- 归纳推理
- 演绎推理与归纳推理的区别
** 第 2 篇 思考的逻辑
首先，要找出将这些思想联系起来的逻辑框架，并确定其逻辑顺序（见第6章“应
用逻辑顺序”），然后概括总结出各组思想的隐含意义——即所谓的归纳跃进
（inductive leap）（见第7章“概括各组思想”）。

这一过程称为冷静思考（Hard-Headed Thinking）。学习和应用这一步骤都有一
定的难度；但是，如果你确实想了解自己的思维，就必须掌握冷静思考的技巧。
因此，希望你多花一点时间，了解和掌握思考的技巧。
*** 第 6 章 应用逻辑顺序
金字塔原理的第二条规则规定：所有列入同一组中的思想必须具有某种逻辑顺序。
**** 时间顺序
- 根据结果寻找原因
- 揭示隐含的逻辑思路
**** 结构顺序
结构顺序就是当你使用示意图、地图、图画或照片想象某事务时的顺序。
- 创建逻辑结构 (MECE: Mutually exclusive, collectively exhaustive)
- 描述逻辑结构 (一旦建立起逻辑结构，就可以按照自上而下、自左而右的顺序依次描述各个部分)
- 修改逻辑结构 (用结构顺序概念检查思路)
**** 程度顺序 (重要性顺序)
- 创建分组
- 识别, 调整不适当的分组
*** 第 7 章 概括各组思想
**** 总结句避免使用 “缺乏思想” 的句子
思想的表达方式与其分组基础无关，可以是行动性语句，即告诉读者要做什么事；也可以是描述性语句，即告诉读者关于某些事的情况。
- 概括行动性思想（介绍采取的行动、行为、动作、步骤、流程）时，应说明采取行动后取得的结果（效果、达到的目标）。
- 概括描述性思想（介绍背景、信息）时，应说明这些思想具有的共同点的含义（共同点的意义）。
**** 总结句要说明行动产生的结果／目标
- 该组行动、步骤之间必须相互独立不重叠，完全穷尽无遗漏。
- 总结概括的语句，必须说明完成各行动步骤后导致的直接结果，且措辞必须明确、具体。
- 先用明确的语句表述各行动、步骤、流程等，然后区分不同的抽象层次，再直接从各行动、步骤、流程等总结概括出行动的结果。
**** 找出各结论之间的共性
- 找出结构上的共性
- 为什么只有这 4 个变量，而没有其他变量？这 4 个变量之间有哪些共同点，使作者把它们列在一起？
  如果你试图用更明确的语言表达这些思想，以找出其中的逻辑顺序，你就会发现原作者实际上谈论的是 4 个步骤，
** 第 3 篇 解决问题的逻辑
一个理想的流程：
- 界定问题→结构化→分析/找到→组成金字塔
- (分析问题/解决方案/与他人交流)
提高写咨询报告效率的秘诀是：
1. 界定问题
2. 有条理地搜集和分析数据，转换为金字塔的形式
*** TODO 第 8 章 界定问题
判断 问题 是否 存在， 通常 要看 经过 努力 得到 的 结果（ 现状）， 与 希望 得到 的 结果（ 目标） 之间 是否 有 差距。

由 某一 特定 背景 导致 的 某一 特定 结果， 称为 非 期望 结果（ R1, 即 现状， Undesired Result）。 “问题” 是指 你 不喜欢 某一 结果（ 比如 销售额 降低）， 想得到 其他 结果（ 比如 销售额 增长）， 称为 期望 结果（ R2, 即 目标， DesiredResult）。 解决 方案 则是 指 如何 从 现状 R1 到 目标 R2，
**** 界定问题的框架
- 展开说明框中的各要素
- 把 "界定的问题" 写成序言
**** 展开问题的各要素
- 切入点/序幕（Starting Point/Opening Scene）
- 困扰／困惑（Disturbing Event）
- 现状，非期望结果（R1, Undesired Result）
- 目标，期望结果（R2, Desired Result）
**** 发掘读者的疑问
**** 开始写序言
**** 实战案例
*** TODO 第 9 章 结构化分析问题
分析问题的标准流程是：收集信息→描述发现→得出结论→提出方案
**** 从信息资料入手
**** 设计诊断框架
**** 使用诊断框架
**** 建立逻辑树
**** 是非问题分析
** 第 4 篇 演示的逻辑
*** 第 10 章 在书面上呈现金字塔
写作长篇文章时，在页面上呈现金字塔层级的方法很多，最常见的有：
- 多级标题法
- 下划线法
- 数字编号法
- 行首缩进法
- 项目符号法
**** 突出显示文章的框架结构
Emacs Org-mode wins here.
**** 上下文之间要有过渡
*** 第 11 章 在 PPT 演示文稿中呈现金字塔
**** 设计文字 PPT 幻灯片
- 每次只演示和说明一个论点
- 用逐级展开呈现，提高趣味性
**** 设计图表 PPT 幻灯片
图表标题标明论点，还能最大限度地减少混淆，因为不同的观众有不同的观点、
背景和兴趣，关注问题的角度也不同。好的图表标题能立刻让观众的注意力集中
在你希望强调的数据方面。
**** 故事梗概                                                          :best:
1) 序言尽量写得详细，把每个你想说的词汇按照你希望的顺序写下来。这样做不仅可以保证没有遗漏，还可以再次检查你回答的问题是否仍然是受众想问的。
2) 用写故事梗概的形式。每张幻灯片写作的顺序，从上往下依次为序言各要素、关键句要点和关键句下一层次的论点。
3) 初步决定你准备采用的呈现方法。这时你可能还没有准确的数据，但只要知道数据的类型和想要表现何种关系即可。
4) 准备好每张幻灯片的讲稿，确保整个演示像讲故事一样流畅。
5) 完成幻灯片的设计和绘图。
6) 排练，排练，再排练！
*** 第 12 章 在字里行间呈现金字塔
**** 画脑图（在大脑中画图像）
**** 把图像复制成文字
** 附录 1 在无结构情况下解决问题的方法
** 附录 2 序言结构范例
** TODO 附录 3 本书要点汇总
*** 第 1 章: 为什么要用金字塔结构
1. 为了交流方便，必须将思想（观点、结论、要点、论点、论据、建议、行动、步骤等）归类分组。
2. 将分组后的思想，按照不同层次，进行抽象提炼、总结概括，搭建金字塔。
3. 向读者介绍（传递、阐述、论证）思想最有效的途径，是结论先行，自上而下表达。
4. 金字塔中的思想，应遵守 4 个基本原则。
5. 条理清晰的关键，是把你的思想组织成金字塔结构，并在写作前用金字塔原理检查。
{{{begin-summary}}}
金字塔原理 的 4 个基本原则:
- 结论先行：每篇文章只有一个中心思想，并放在文章的最前面。
- 以上统下：每一层次上的思想必须是对下一层次思想的总结概括。
- 归类分组：每一组中的思想必须属于同一逻辑范畴。
- 逻辑递进：每一组中的思想必须按照逻辑顺序排列。
{{{end-summary}}}
*** 第 2 章: 金字塔内部的结构
1. 金字塔结构的各个层级上包括各种思想；思想使受众（包括读者、听众、观众或学员）产生疑问。
2. 在纵向方向上，各分支、各层级上的思想，与读者进行疑问/回答式对话。
3. 在横向方向上，各种思想以演绎推理或归纳推理方式回答读者的疑问，但两种方式不可同时使用。
4. 序言的讲故事形式是为了提醒读者，文章将回答的读者最初的疑问。
5. 序言包括背景、冲突、读者的疑问和作者的回答。冲突因背景而产生，背景和冲突都是读者已知的事实。
6. 冲突导致读者提出疑问，而文章将回答读者的疑问。
{{{begin-summary}}}
- 金字塔结构中的逻辑关系
- 各种思想纵向相关（疑问／回答式对话）
- 各种思想横向相关（演绎／归纳，MECE 原则）
- 金字塔顶端思想回答的疑问，来自读者已知的事实
- 序言引出读者最初的疑问
{{{end-summary}}}
*** 第 3 章: 如何构建金字塔
- 自上而下法
  1. 确定作者想论述的主题
  2. 设想读者的疑问
  3. 给出答案
  4. 检查背景和冲突是否引发读者提出疑问
  5. 证实答案
  6. 填写关键句要点
- 自下而上法
  1. 列出所有作者想表达的要点
  2. 找出各要点之间的关系
  3. 得出结论
  4. 倒推出序言
{{{begin-summary}}}
构建金字塔:
- 确定主题
- 设想疑问
- 给出答案
- 检查背景和冲突是否引发读者提出疑问
- 证实答案
- 填写关键句要点
{{{end-summary}}}
** 参考文献
* TODO Beast Machines: Transformers (cartoon)
** Introduction
- http://tfwiki.net/wiki/Beast_Machines:_Transformers_(cartoon) ::
  The show follows the adventures of the core Beast Wars cast upon their
  return home to Cybertron; there, Optimus Primal and his crew find that
  the whole planet is abandoned, and the streets are patrolled by
  mindless Vehicon drones serving Megatron, who somehow escaped his
  captivity.

  Worse still, they learn that they are infected with a deadly virus
  that will kill them in a matter of hours. Salvation (我已经忘了救赎有
  拯救的含义在里面...) comes from the mysterious supercomputer known as
  the Oracle, who sees them fit to complete its mission of a planetwide
  "reformatting", and turns them into *technorganic warriors*, a perfect
  blend of organic and technological matter.

  As the show progresses, Primal and his fellow Maximals learn to
  balance their technological side with their newly introduced organic
  aspects, mastery coming in slow stages. Unlike the previous conflict,
  where sides had been roughly equal, the four original Maximals were
  quite *outnumbered by their Vehicon enemies*, and the battles took on a
  "*guerilla warfare*" feel, with the Maximals using sewers and
  underground levels to their advantage and avoiding surface levels
  unless for combat purposes. As the show progresses, two brand-new
  Maximals and a returning face boost their numbers.

  Initially, Optimus is driven by a crusade to restore the organic above
  the technological and to right his failure to stop Megatron. Over
  time, it becomes increasingly clear that he's becoming obsessed and
  overzealous. At the midpoint, after Cybertron is almost destroyed, he
  realises that the point should be to *create a balance of organic and
  technological, not a supremacy*. Under this new, saner cause, the
  Maximals eventually turn Cybertron into an technorganic paradise,
  though at the cost of their leader's life.
  (最后那也叫天堂... 一片荒地啊. 好遗憾 Megatron 失败了)
- [[https://www.youtube.com/watch?v=KWWXw5SMIP0][Youtube: Beast Wars Megatron Has a God Complex]] :: 一个不错的合集
** Quotes
- http://www.imdb.com/title/tt0189315/quotes ::
  + Optimus Primal: What's wrong, Megatron? Is your"single elegant machine" having trouble multitasking?
  + Tankorr: Oh, I'm sorry. Were you happier when my vocabulary was limited to,'TANKORR SMASH'?
** Season 1
Season 1 largely centers on the Maximals' efforts to find out what has
happened to them, as they arrive on Cybertron with no memories. In
addition to Megatron and the core Maximal cast, three new Vehicon
generals are introduced, as well as the new Maximal Nightscream. By
the end of the season, Optimus Primal has been driven down a road of
extremism, and an apocalyptic confrontation marks the season finale...
*** The Reformatting
Escaping from strange new foes (敌人) and unable to transform, the four
surviving Maximals encounter a mysterious supercomputer which remakes
them into a new kind of Transformer.
*** Master of the House
*** Fires of the Past
*** Mercenary Pursuits
*** Forbidden Fruit
*** The Weak Component
*** Revelations Part I: Discovery
*** Revelations Part II: Descent
*** Revelations Part III: Apocalypse
*** Survivor
*** The Key
*** The Catalyst
*** End of the Line
** Season 2: Battle for the Spark
The ultimate face-off (对峙) at the end of Season 1 is resolved in a most
unusual and cerebral manner, setting the tone for Season 2 as Primal
realizes his mission is one of balance, not extremism. Silverbolt
rejoins the Maximal ranks, a new Maximal arrives from off-world, and
two dangerous new generals join Megatron's side as the Maximals search
for the lost Sparks of their brethren and battle to regain control of
Cybertron.
*** Fallout
*** Savage Noble
*** Prometheus Unbound
*** In Darkest Knight
*** A Wolf in the Fold
*** Home Soil
*** Sparkwar Pt. I: The Strike
*** Sparkwar Pt. II: The Search
*** Sparkwar Pt. III: The Siege
*** Spark of Darkness
*** Endgame Pt. I: The Downward Spiral
*** Endgame Pt. II: When Legends Fall
*** Endgame Pt. III: Seeds of the Future
* 论持久战
毛泽东. 论持久战 (Kindle Location 70).  . Kindle Edition. 论持久战 （一九三八年五月）
** 问题的提起
这样，日本在中国抗战的长期消耗下，它的经济行将崩溃；在无数战争的消磨中，
它的士气行将颓靡。中国方面，则抗战的潜伏力一天一天地奔腾高涨，大批的革
命民众不断地倾注到前线去，为自由而战争。所有这些因素和其他的因素配合起
来，就使我们能够对日本占领地的堡垒和根据地，作最后的致命的攻击，驱逐日
本侵略军出中国。（斯诺：《西北印象记》）
** 问题的根据
中日战争不是任何别的战争，乃是半殖民地半封建的中国和帝国主义的日本之间
在二十世纪三十年代进行的一个决死的战争。全部问题的根据就在这里。分别地
说来，战争的双方有如下互相反对的许多特点。

...

我们依然是一个弱国，我们在军力、经济力和政治组织力各方面都显得不如敌人。
战争之不可避免和中国之不能速胜，又在这个方面有其基础。然而第二，中国近
百年的解放运动积累到了今日，已经不同于任何历史时期。各种内外反对力量虽
给了解放运动以严重挫折，同时却锻炼了中国人民。
** 驳亡国论
国际的条件，使得中国在战争中不是孤立的，这一点也是历史上空前的东西。历
史上不论中国的战争也罢，印度的战争也罢，都是孤立的。惟独今天遇到世界上
已经发生或正在发生的空前广大和空前深刻的人民运动及其对于中国的援助。
** 妥协还是抗战？腐败还是进步？
第二是中国方面。中国坚持抗战的因素有三个：其一，共产党，这是领导人民抗
日的可靠力量。又其一，国民党，因其是依靠英美的，英美不叫它投降，它也就
不会投降。又其一，别的党派，大多数是反对妥协、拥护抗战的。这三者互相团
结，谁要妥协就是站在汉奸方面，人人得而诛之。一切不愿当汉奸的人，就不能
不团结起来坚持抗战到底，妥协就实际上难于成功。

由此可作结论：妥协的危机是存在的，但是能够克服。因为敌人的政策即使可作
某种程度的改变，但其根本改变是不可能的。中国内部有妥协的社会根源，但是
反对妥协的占大多数。国际力量也有一部分赞助妥协，但是主要的力量赞助抗战。
这三种因素结合起来，就能克服妥协危机，坚持抗战到底。
** 亡国论是不对的，速胜论也是不对的
因此，我们客观地并全面地估计到一切敌我情况，指出只有战略的持久战才是争
取最后胜利的唯一途径，而排斥毫无根据的速胜论。我们主张为着争取最后胜利
所必要的一切条件而努力，条件多具备一分，早具备一日，胜利的把握就多一分，
胜利的时间就早一日。我们认为只有这样才能缩短战争的过程，而排斥贪便宜尚
空谈的速胜论。
** 为什么是持久战？
然而情况是继续变化的。战争过程中，只要我能运用正确的军事的和政治的策略，
不犯原则的错误，竭尽最善的努力，敌之不利因素和我之有利因素均将随战争之
延长而发展，必能继续改变着敌我强弱的原来程度，继续变化着敌我的优劣形势。
到了新的一定阶段时，就将发生强弱程度上和优劣形势上的大变化，而达到敌败
我胜的结果。
** 持久战的三个阶段
- 第一个阶段，是敌之战略进攻、我之战略防御的时期。
- 第二个阶段，是敌之战略保守、我之准备反攻的时期。
- 第三个阶段，是我之战略反攻、敌之战略退却的时期。

中国人民在这样长期和残酷的战争中间，将受到很好的锻炼。参加战争的各政党
也将受到锻炼和考验。统一战线必须坚持下去；只有坚持统一战线，才能坚持战
争；只有坚持统一战线和坚持战争，才能有最后胜利。果然是这样，一切困难就
能够克服。跨过战争的艰难路程之后，胜利的坦途就到来了，这是战争的自然逻
辑。
** TODO 犬牙交错的战争
这种犬牙交错的形态，表现在下述的几种情况上:
- 内线和外线 :: 抗日战争是整个处于内线作战的地位的；但是主力军和游击队的关系，则是主力军在内线，游击队在外线，形成夹攻敌人的奇观。
- 有后方和无后方 :: 利用国家的总后方，而把作战线伸至敌人占领地之最后限界的，是主力军。脱离总后方，而把作战线伸至敌后的，是游击队。
- 包围和反包围 ::
  从整个战争看来，由于敌之战略进攻和外线作战，我处战略防御和内线作战地位，无疑我是在敌之战略包围中。这是敌对于我之第一种包围。
  由于我以数量上优势的兵力，对于从战略上的外线分数路向我前进之敌，采取战役和战斗上的外线作战方针，就可以把各路分进之敌的一路或几路放在我之包围中。这是我对于敌之第一种反包围。
  再从敌后游击战争的根据地看来，每一孤立的根据地都处于敌之四面或三面包围中，前者例如五台山，后者例如晋西北。这是敌对于我之第二种包围。
  但若将各个游击根据地联系起来看，并将各个游击根据地和正规军的阵地也联系起来看，我又把许多敌人都包围起来，
  例如在山西，我已三面包围了同蒲路（路之东西两侧及南端），四面包围了太原城；河北、山东等省也有许多这样的包围。这又是我对于敌之第二种反包围。这样，敌我各有加于对方的两种包围，
  大体上好似下围棋一样，敌对于我我对于敌之战役和战斗的作战，好似吃子，敌的据点（例如太原）和我之游击根据地（例如五台山），好似做眼。
  如果把世界性的围棋也算在内，那就还有还有第三种敌我包围，这就是侵略阵线与和平阵线的关系。敌以前者来包围中、苏、法、捷等国，我以后者反包围德、日、意。
  但是我之包围好似如来佛的手掌，它将化成一座横亘宇宙的五行山，把这几个新式孙悟空——法西斯侵略主义者，最后压倒在山底下，永世也不得翻身。
  如果我能在外交上建立太平洋反日阵线，把中国作为一个战略单位，又把苏联及其他可能的国家也各作为一个战略单位，又把日本人民运动也作为一个战略单位，
  形成一个使法西斯孙悟空无处逃跑的天罗地网，那就是敌人死亡之时了。实际上，日本帝国主义完全打倒之日，必是这个天罗地网大体布成之时。这丝毫也不是笑话，而是战争的必然的趋势。
- 大块和小块

这样看来，长期而又广大的抗日战争，是军事、政治、经济、文化各方面犬牙交
错的战争，这是战争史上的奇观，中华民族的壮举，惊天动地的伟业。
** 为永久和平而战
** 能动性在战争中
** 战争和政治
** 抗日的政治动员
** 战争的目的
** 防御中的进攻, 持久中的速决, 内线中的外线
** 主动性, 灵活性, 计划性
** 运动战, 游击战, 阵地战
** 消耗战, 歼灭战
** 乘敌之隙的可能性
** 抗日战争中的决战问题
** 兵民是胜利之本
** 结论
* 一看就懂的经济常识全图解
** 第 1 章　树立经济学的思维方式——微观与宏观经济学
*** 起源发展：微观经济学的追踪
亚当·斯密的《国富论》是公认的第一本真正意义上的经济学著作。而亚当·斯密
本人也被认为开创了近代政治经济学，被誉为“经济学之父”。
亚当·斯密的最大贡献是他提出了“看不见的手”的学说。

- 微观经济学 ::
  是以企业、家庭和单个市场作为研究对象，研究供求行为与价格之间的关系等经
  济行为。它研究的对象是个别经济单位（居民户、厂商）的经济行为，解决的问
  题是 *资源配置* ，中心理论是价格理论，研究方法是个量分析，研究经济变量的单
  项数值如何决定。
- 宏观经济学 ::
  是研究一个国家整体经济的运行及政府运用经济政策来影响整体经济等宏观经济
  问题的学科。它研究的对象是整个经济，解决的问题是 *资源利用* ，中心理论是国
  民收入决定理论，研究方法是总量分析。微观经济学与宏观经济学的关系：两者
  互相补充，资源充分利用和资源合理配置是经济学的两个方面。微观经济学是宏
  观经济学的基础，假如宏观经济学研究森林的特征，微观经济学则是考察构成森
  林的树木。微观经济学与宏观经济学只是研究对象有所分工，两者的立场、观点
  和方法并无根本分歧。

经济学研究的基本问题: 简单来说，经济学是一门研究人类行为及如何将有限或者稀缺资源进行合理配置的社会科学。
*** 微观经济学基础：假设和主体
假设:
- 合乎理性的人
- 充分完全的信息
主体:
- 微观经济学的主要范围包括消费者选择，厂商进行的供给和收入分配。
- 微观经济学主要理论有：
  + 均衡价格理论、
  + 消费者行为理论、
  + 生产者行为理论（包括生产理论、成本理论和市场均衡理论）、
  + 分配理论、
  + 一般均衡理论与福利经济学、
  + 市场失灵与微观经济政策。
*** 创新与发展：不断开拓创新的微观经济学
- 早期萌芽阶段（1662—1837）早期萌芽阶段 ::
  主要是经济学思想的起源。其标志人物分别是，魁奈、斯密和李嘉图。
- 产生阶段（1838—1947） ::
  在自然科学迅猛发展的影响下，西方经济学开始向微观和宏观两端发展。特别是
  以边际分析的价值论、市场（价格）论和分配论作为核心的微观经济理论，已经
  在这一时期奠定了基础，在系统化方面比宏观经济理论远远走前了一步。
- 形成和发展阶段（1948—1960） ::
  + 一般经济均衡的严格理论体系
  + 投入产出分析
- 最新发展阶段（1961年至今） ::
  公理化经济学的出现，使得经济学家与数学家之间的对话变得更加频繁。经济学
  开始影响数学，其典型的例子就是角谷定理、集值映射的积分理论、近似不动点
  计算的算法以及方程组的近似解的算法。数学思想开始全面向经济学渗透，经济
  学也在不断地为自己铸造新的“武器”，各种经济分析方法汇集，出现了经济学发
  展史上的大会合时期。20世纪60年代以来，微观经济学的研究课题主要有：
  + 不确定性和信息 (主观概率加深了人们对证券市场、保险市场、市场信息及搜集行为的认识，尤其是在经济系统中考虑了信息结构)
  + 总需求函数
  + 社会选择理论、(通过个人选择来确定社会选择)
  + 不完全竞争理论(竞争分为垄断竞争、寡头垄断和完全垄断三种。同消费者日常生活关系最密切的是垄断竞争)
  + 博弈论
*** 宏观经济学：研究经济大趋势的学问
- 最早把经济学分为微观与宏观两部分的是凯恩斯。
- 宏观经济学是研究总需求和总供给的学问，它研究经济总量的决定及其变动。
  它是用总量分析研究一个国家的资源充分利用的问题.
- 宏观经济学是从整体上考察一国经济总体运行及其规律的一门学科，
  最终是为了实现充分就业、物价稳定、经济持续增长、国际收支平衡这四大目标
*** TODO 宏观经济学的核心：国民收入决定理论
*** 宏观经济学关键词：总需求、就业、货币
*** 宏观经济学的理论基石：凯恩斯主义
*** 衡量一国的经济发展指标：GDP 和 GNP
*** GDP 失灵：无效的 GDP 与消失的 GDP
*** 名义 GNP 和实际 GNP：钱不一定值钱
*** GDP 和社会福利：GDP 增加，福利不一定提高
第 2 章　经济学的新方法——博弈论
博弈论简介：带你走进博弈论
信息不对称：隔行如隔山
智猪博弈：做大猪还是做小猪
枪手博弈：先发优势与后发制人
斗鸡博弈：前进还是撤退
酒吧博弈：混沌系统中的策略
重复博弈：杜绝一次性交易
第 3 章　市场运行的左右手——供给和需求
供给：面包的供给是工厂的决定
需求： 洛阳纸贵的原因何在
供给曲线和需求曲线：商品市场的 “线性” 变动
均衡价格：供需之间妥协的结果
供给和需求的变动：为什么钻石贵过水
价格弹性：价格对市场的敏感度有多大
蛛网理论：丰产并不代表着丰收
价值规律：价格围绕价值的上下波动
第 4 章　花钱是一门艺术——消费者理论
消费者偏好：为什么奥迪到中国需要加长
消费者效用：花钱就是为了买个高兴
消费需求：渔翁为什么只要小鱼
消费者决策：是买 “春兰” 空调还是买 “美的” 空调
预算约束：高收入才能高消费
冲动消费：女性消费跟财富无关
炫耀性消费：是买 “江诗丹顿” 手表还是买 “上海” 手表
替代效应与收入效应：闲暇时间如何打发
示范效应：朋友对购物的影响
第 5 章　国民经济活动的体检表——经济指标
恩格尔系数：“吃” 出来的温饱、小康、富裕
消费者物价指数：通货膨胀的预警器
消费者信心指数：敢不敢消费很重要
负担系数：亿老年人如何养老
基尼系数：反映贫富差异的曲线
零售指数：家电下乡为什么可以拉动经济
道琼斯指数：美国股票市场的晴雨表
第 6 章　经济与政治能否独立——市场与政府
市场基础：专业化和劳动分工
市场机制：亚当 · 斯密那只 “看不见的手”
市场经济：冲破小农经济的藩篱
市场功能：市场贸易促进了社会发展
政府的经济职能：自由市场下，政府需要做什么
公平和效率：政府调控市场的真实目的
第 7 章　微观经济的核心——市场与商品
产权：市场交易的第一前提
市场：买与卖的交易场所
市场原则：自愿、平等、公平、诚实信用
道德风险：自行车被盗的危险
互补品与独立品：物品之间的替代与并存
吉芬商品：不遵守供求规律的例外商品
第 8 章　绝不做亏钱的买卖——生产与成本
利润最大化：逐利，生产者并非天生勤奋
边际分析法：经营之神的经营之道
规模经济：企业的规模并不是越大越好
范围经济：巧妙搭配，不让资源闲置
沉没成本：不可挽回的损失不计较
边际产量递减：为什么员工增加了，产量却在减少
生产成本及分类：生产者要考虑哪些成本 “代价”
成本最小化：控制成本才最具竞争力
第 9 章　经营压力下的商业交锋——市场竞争
完全竞争：没有干扰的小麦市场
垄断竞争：垄断企业之间的差异生存
垄断：谁是油价上涨的推手
托拉斯：从生产商到销售商的高端垄断联合
卡特尔：同类企业瓜分市场的阴谋
差别定价：同机不同价的歧视
价格战争：厂商 “厮杀”，消费者吃亏
兼并：企业扩张的快捷方式
第 10 章　社会财富的再分配——税收
社会再分配：最正当的 “劫富济贫” 计划
税收：个人收入与社会公平的调节器
累进税：越富的人交税越多
增值税：我国第一大税种
所得税：财富分割的利器
庇古税：谁污染，谁治理
拉弗曲线：里根减税的经济学道理
第 11 章　宏观经济调控的左手——财政政策
政府预算：政府的预算报告
财政赤字：资不抵债的政府
财政政策：宏观经济刺激与调控的政策
减税：刺激经济增长的特殊方法
财政补贴：财政安排的专项援助
转移支付：财政资金的无偿转移
第 12 章　经济运行的润滑剂——货币和商业银行
货币：不仅仅是钱那么简单
货币流通：央行究竟要发行多少钱
货币制度：没有规矩，不成方圆
银行：金融家族的 “老大哥”
商业银行：银行体系的主体
金融体系：组织、监管、市场
金融市场：资本和货币交易的地方
金融中介机构：投资银行、保险、财务公司
电子金融：未来的金融主宰者
货币危机：金融体系中的多米诺骨牌效应
第 13 章　最后的贷款人——中央银行和货币政策
中央银行：国家经济的大动脉
货币政策：钱的增多与减少
货币传导机制：货币政策是如何发挥作用的
利率政策：经济调控的又一杠杆
存款准备金率：银行放出多少贷款对经济的影响
再贴现政策：根据需要调整再贴现率
金融管制：预防金融风险的管制
第 14 章　手中的钱是如何变没了——货币与通货
货币和通货膨胀：钱多了注定了不值钱
恶性通货膨胀：谁来为消失的财富埋单
通货紧缩：物价过低并非是好事
货币升值：人民币升值是好事，还是坏事
货币贬值：调节进出口的经济手段
第 15 章　工作是经济发展的重中之重——劳动就业
充分就业：实现所有人的工作理想
失业：还有多少人为饭碗发愁
菲利普斯曲线：通货膨胀同失业的 “亲密关系”
大学生就业问题：学历越来越不值钱
人口红利：可预知的人口红利及其影响
* DONE 书法离钩
  CLOSED: [2017-10-07 Sat 21:06]
明•潘之淙

http://www.moedict.org/#'鉤

贪夫钩利，烈士钩名，一任游戏清波，总离不得这个钩字。虽然，钩可离也。能
者离亦是，不离亦是；不能者离亦非，不离亦非。何以故？欲知离钩，当先知吞
钩。善吞钩者，无往非钩。

虽然，志不正而神何以清？欲不净而气何以雄？非雅无以言致，非博无以成趣，晋岂尽王夷甫一流清言韶令而已哉！

故论世汉则古雅多质，晋则逸韵自赏，唐则清峭取险，宋则姿媚求工，世可殊而
法不变也。语境则醉墨濡头者豪于致，败毫成冢者勇于力，怒猊渴骥者奇于气，
惊沙舞剑者悟于神，绿蕉覆云者博于趣，脱巾啸傲者逸于姿，境可殊而法不变也。

- 六艺之五，有曰六书，而书法乃大备。六书者，一象形，二指事，三会意，四谐声，五假借，六转注也 ::
  #+BEGIN_QUOTE
    《周礼 · 保氏》：“养国子以道，乃教之六艺：一曰五礼，二曰六乐，三曰五射，四曰五驭，五曰六书，六曰九数。”
  #+END_QUOTE
  + 象形者，象其物形，随体诘诎，而画其迹也。
  + 指事者，直著其事，加物于象形之文，指而可识也。
  + 会意者，比类合义，以见指捴，或合体而兼义，或反文而取意。
  + 谐声者，主母以定形，因母以主意，而附他字为子，以调合其声也。
  + 假借者，无义之义，本非己有，因他所授也。
  + 转注者，展转其声，注释其字，而后知也。

DITCHED.
* 刻意练习
** 推荐序
西蒙在文中首次提出专业技能习得的十年定律（10 years rule），西蒙推测，国际象棋大师能够在长时记忆系统中存储 5 万 ~ 10 万个棋局组块，获得这些专业知识大概需要 10 年。

首先，不同专业领域的技能习得时间与练习时间并不存在一个1万小时的最低阈值。例如，优秀专业演员的专业技能习得往往是3500小时；记忆类专家技能的习得也并不需要1万小时，而是数百小时。

1 万小时定律是有帮助的，但真正实现，还需要坚持不懈，并练习上很多个周期。（The 10000 hour rule helps. But to beachieved，it needs persistence and passing through a lot of cycles.）

这或许才是西蒙的十年定律对我们真正的启发: *耐心地、谦虚地保持大时间周期的刻意练习。*

{{{begin-block(吐槽)}}}
额, 不太喜欢阳志平的推荐序. 驳斥 Gladwell 的 10000 小时理论时有点扯.
其实这是从本书提取出来的观点, 作者还算良心说了 Gladwell 对在哪儿 (长时间的刻意练习很重要),
错在哪儿 (10000 个小时不是一个奇特的数字, 这个数字在很多行业不一样, 而且 10000 个小时不是承诺, 不能保证你能成功).
{{{end-block}}}
** 作者声明
*** 引言　天才存在吗 //001
- 莫扎特的完美音高 ::
  在音乐上，“绝对音高”（absolute pitch）是个技术术语 (“完美音高”,
  perfectpitch）。它异常罕见，大约在每万人中，只有 1 个人具备这种能力。

  这是一个令人震惊的结果。尽管在正常的条件下，每万人中只有 1 人具有完美音
  高，但参加了榊原彩子研究的那些孩子，却个个都拥有。这显然意味着完美音高
  根本谈不上是只有幸运的少数人才拥有的天赋，而是一种只要经过适度的接触和
  训练，几乎人人都可以培养和发展的能力。

  我们的大脑拥有和莫扎特这样的 “天才” 相同的适应能力，“天才” 只是更多地利用了这种适应能力。
- “天才” 是训练的产物 ::
  随着时间的推移，他将自己的三分跳投训练得如此娴熟自然，动作优美，以至于人们以为他天生就是个杰出的三分射手。他只是利用了他的天才，他真正的天才。
- 本书将告诉我们什么 ::
  学习不再是挖掘某人潜力的方式，而是发展这种潜力的方式。我们可以创造自己的潜力。

  想提高你的网球水平吗？刻意练习。写作水平？刻意练习。销售技能？刻意练习。
** 第 1 章　有目的的练习
事实上，音乐批评家安东尼·托马西尼（AnthonyTommasini）在《纽约时报》上
一度发表评论，认为自柯尔托的时代以来，人类的音乐能力得到了大幅度提高，
以至于柯尔托当时的水平，如果放在今天，可能连茱莉亚音乐学院的入学考试都
通不过。

一旦某个人的表现达到了 “可接受” 的水平，并且可以做到自动化，那么再多
“练习” 几年，也不会有什么进步，而且还会缓慢退化。有目的的练习则更加有效。

有目的的练习 VS 天真的练习
- 所谓“天真的练习”，基本上只是反复地做某件事情，并指望只靠那种反复，就能提高表现和水平。
- 有目的的练习的四个特点:
  + 有目的的练习具有定义明确的特定目标
  + 有目的的练习是专注的
  + 有目的的练习包含反馈 (不论你在努力做什么事情，都需要反馈来准确辨别你在哪些方面还有不足，以及怎么会存在这些不足)
  + 有目的的练习需要走出舒适区 (如果你从来不迫使自己走出舒适区，便永远无法进步)

他就如同一名在 30 年的时间里一直以同样的方式弹同样一些曲子的钢琴家。

遇到瓶颈怎么办
- 试着做不同的事情，而非更难的事情(不要死磕,换一个思路)
- 并非达到极限，而是动机不足

因此，我们在这里简单地总结有目的的练习：
#+BEGIN_QUOTE
  走出你的舒适区，但要以专注的方式制订明确的目标，为达到那些目标制订一
  个计划，并且想出监测你的进步的方法。哦，还要想办法保持你的动机。对想
  要提高自己的每个人来讲，这些是让你有一个卓越开端的秘诀——但依然只是开始。
#+END_QUOTE

有目的的练习还不够, 需要的是刻意练习

我们把这种预先固定的模式称为“检索结构”（retrieval structure），它使得
史蒂夫可以着重记住三个数字和四个数字的数字组，一组一组地记，然后在脑海
中记住这些单个的组适合放在检索结构中的哪个位置。

雷妮设计的记忆术是：根据她听到的数字是什么，再决定使用 什么方法来记住
它们。由于这种方法不具备史蒂夫采用方法的那种一致性，因此，她没法记住超
过 20 位数字。

{{{begin-block(吐槽)}}}
这一段为了引出特意练习, 有意和 "有目的的联系" 划清界限. 举的例子也没啥说服力,
retrieval structure 的优势其实只在规则简单/固定, 相比下雷妮很容易忘了自己索引的 key (的模式).
{{{end-block}}}
** 第 2 章　大脑的适应能力
一个人遇到的挑战越大，大脑的变化就越大，学习也越高效，但是过分逼迫自己
可能导致倦怠。因此，处在舒适区之外却离得不太远的挑战，能使大脑的改变最
为迅速。
*** 伦敦出租车司机的海马体后部也同样“膨胀”，但其中充满的是脑组织，而不是肌肉纤维.
简单地讲，人类身体的适应能力令人难以置信。这种适应能力，不仅仅是骨骼肌
肉的，还是心脏、双肺、循环系统、身体的能量储存以及更多其他方面的，凡是
与身体爆发力和耐力相关的各个方面，都包括在内。尽管适应能力依然存在极限，
但并没有迹象表明我们已达到那些极限。
*** 大脑拥有无限的适应能力 (盲人大脑如何“重新布线”)                    :best:
研究人员让研究对象每周来实验室3次左右，连续3个月保持这样的频率，并且每
次花30分钟来训练他们的视力。研究人员要求他们观察一张小小的图片，将图片
放置在与其形状非常相似的背景之中；也就是说，图片与背景之间的对比度很小。
要观察图片，需要高度集中注意力，还得付出巨大的精力。随着时间的推移，研
究对象学会了迅速而准确地辨别图片。到3个月的训练结束时，研究人员组织了
测试，以了解研究对象能够观察多大尺寸的图片。总体而言，研究对象能够阅读
比他们在刚开始训练时小了60%的文字，而且，每位研究对象都改进了视力。此
外，在训练之后，研究对象能够不戴眼镜读报了，这是他们中大多数人在接受训
练之前无法做到的。不但如此，他们读报的速度也比从前更快了。

令人惊奇的是，所有这些改进，并非由眼睛本身的变化造成。研究对象的眼睛还
和从前一样，晶状体依然缺乏伸缩性，而且难以聚焦。相反，这些改进是由他们
大脑中某些部位的改变引起的，这些部位负责解读来自眼睛的视觉信号。
*** 走出舒适区的重要性
因此，要使改变不断进行下去，你必须不断地加码：跑得更远一些、更快一些，并且爬坡跑。
如果你不继续给自己施加一些压力，身体将会保持体内平衡，尽管此时的体内平衡不同于以前，
但你将停下改进的脚步。

But not too much, 小心受伤
*** 练习改变大脑结构
- 训练对大脑的影响随着年龄递减
- 已经超常发展了某项技能或能力的人，在另一些行业或领域则出现了退化。代价(顾此失彼,此消彼长)
- 由训练引起的认知和生理变化需要继续保持。
*** 潜能可以被构筑
** 第 3 章　心理表征
在任何一个行业或领域，技能与心理表征之间的关系是一种良性循环：你的技能越娴熟，创建的心理表征就越好；而心理表征越好，就越能有效地提升技能。

*** 偶然的盲棋大师
国际象棋大师并没有培养令人不可思议的记忆力，来记住棋盘上单个的棋子；相
反，他们的记忆是取决于背景的，也就是说，只针对那些在正常棋局中出现的棋
子位置进行记忆。

5万个数据块: 研究国际象棋的大师已经在其他棋局中见过大量的这种“数据块”，
它们相互之间有关联。研究表明，这些“数据块”是按层级整理的，低水平的构成
一组，中等水平的构成一组，高水平的又构成另一组。

既见树木，又见森林: 简单地讲，一方面，心理表征使大师着眼于全局来观察，
看到“一片森林”，这是新手无法做到的；另一方面，心理表征还使大师可以在必
要时把注意力集中在具体的招法上，观察“一棵树”。

心理表征:
#+BEGIN_QUOTE
  心理表征是一种与我们大脑正在思考的某个物体、某个观点、某些信息或者其
  他任何事物相对应的心理结构，或具体或抽象。
#+END_QUOTE
对于所有的心理表征，有一点是相同的：尽管短时记忆存在局限，但它们使得人
们可以迅速地处理大量信息。事实上，人们可能把心理表征定义为一个概念式的
结构，设计用于回避短时记忆施加在心理加工上的一般局限。

因此，我们总是在自己甚至还不知道的情况下，就创建了这样那样的心理表征。
事实上，没有心理表征，我们连走路（太多的肌肉运动需要协调）、说话（同样
要协调肌肉的运动，再加上要理解所说的话的含义）都做不到，根本无法生活下
去。因此，每个人都拥有并使用心理表征。
*** 心理表征有助于找出规律
不过，对那些了解并喜欢足球的人，特别是那些踢得很好的人来说，这种杂乱根
本算不上杂乱。球员为响应来球而跑动，以及其他球员的跑动，都是有规律可循
的，而且，这其中的规律有着细微的差别，并且在持续不断地变化。最优秀的球
员几乎会在一瞬间就辨别出规律，并做出响应，充分利用对方球员的弱点或本方
努力创造出来的空档。

...

球员在足球这一领域越是取得了卓越的成就，也就越能准确地预测录像中那位接
球的球员下一步会做什么。

经验丰富的攀岩者已经对把手形成了心理表征，这使得他们无须有意识地思考，
便知道看到的是哪一种把手，需要采用哪一类抓握方法。
*** 心理表征有助于解释信息
心理表征的一个重要好处在于，可以帮助我们处理信息：理解和解读它，把它保存在记忆之中，组织它、分析它，并用它来决策。
*** 心理表征有助于组织信息
精心创建的心理表征的一个主要优势是：你可以立即吸收和考虑更多的信息。

科学家对专业诊断医生的研究发现，这些医生往往不会把病人的症状与其他相关
数据视为相互孤立的信息，而是作为更大整体中的一部分来看待，可以说，他们
观察病人的方式，和国际象棋大师观察棋局一样，后者从来不把棋子看成相互没
有联系的孤立个体，而是看成整盘棋中的一部分。
*** 心理表征有助于制订计划
这种写作方法被称为“知识陈述”（knowledge telling），因为差不多是把你脑海中浮现的所有观点一一告诉读者。出色的作家会采用完全不同的方法。
*** 心理表征有助于高效学习
学生之间的差别，在很大程度上最有可能取决于他们能多敏锐地察觉自己所犯的
错误，也就是说，他们对音乐作品的心理表征有多么有效。
** 第 4 章　黄金标准
刻意练习与一般练习的区别十分关键：首先，需要一个已经得到合理发展的行业或领域；其次，需要一位能够布置训练作业的导师。

*** 练习时间是最重要的差别: 最杰出的人，练习时间最长
由于大多数学生每周在音乐导师那里上课的时间是相同的，都是1小时，那么，
学生之间训练效果的主要差别在于，他们花多少时间专门进行单独练习。
*** 刻意练习是什么                                                     :best:
- 不只是有目的的练习
  + 需要一个已经得到合理发展的行业或领域，
  + 其次，刻意练习需要一位能够布置练习作业的导师，以帮助学生提高他的水平。导师必须已经达到一定的水平，并且有一些可以传授给别人的有益的练习方法。
- 简而言之，刻意练习具有以下特点:
  + 刻意练习发展的技能，是其他人已经想出怎样提高的技能，也是已经拥有一整套行之有效的训练方法的技能。训练的方案应当由导师或教练来设计和监管，他们既熟悉杰出人物的能力，也熟悉怎么样才能最好地提高那种能力。
  + 刻意练习发生在人们的舒适区之外，而且要求学生持续不断地尝试那些刚好超出他当前能力范围的事物。因此，它需要人们付出近乎最大限度的努力。一般来讲，这并不令人心情愉快。
  + 刻意练习包含得到良好定义的特定目标，通常还包括目标表现的某些方面；某些方面；它并非指向某些模糊的总体改进。一旦设定了总体目标，导师或教练将制订一个计划，以便实现一系列微小的改变，最后将这些改变累积起来，构成之前期望的更大的变化。改进目标表现的某些方面，使得从业者能够看到他的表现已经通过练习得到了提高。
  + 刻意练习是有意而为的，也就是说，它需要人们完全的关注和有意识的行动。简单地遵照导师或教练的指示去做，还不够。学生必须紧跟他的练习的特定目标，以便能做出适当的调整，控制练习。
  + 刻意练习包含反馈，以及为应对那些反馈而进行调整的努力。在练习过程的早期，大量的反馈来自导师或教练，他们将监测学生的进步、指出存在的问题，并且提供解决这些问题的方法。随着时间的推移，学生必须学会自己监测自己、自己发现错误，并做出相应调整。这种自我监测，需要高效的心理表征。
  + 刻意练习既产生有效的心理表征，又依靠有效的心理表征。提高水平与改进心理表征是相辅相成的，两者不可偏废；随着人们水平的提升，表征也变得更加详尽和有效，反过来使得人们可能实现更大程度的改进。心理表征使人们能监测在练习中和实际的工作中做得怎么样。它们表明了做某件事的正确方法，并使得人们注意到什么时候做得不对，以及怎样来纠正。
  + 刻意练习通过着重关注过去获取的技能的某些特定方面，致力于有针对性地提高那些方面，并且几乎总是包括构建或修改那些过去已经获取的技能；随着时间的推移，这种逐步的改进最终将造就卓越的表现。由于新技能的学习是建立在现有技能基础上的，因此，导师会为初学者提供正确的基本技能，使学生后来能在更高层面上重新学习那些基本的技能。
*** 如何运用刻意练习原则
- 最佳方法是找到优秀导师
*** 1 万小时法则的错与对 //141
- 这一法则具有无法抗拒的吸引力。它很容易被记住。
- 1 万小时法则的最后一个问题在于，尽管格拉德威尔本人并没有说，但许多人把它解释为一种承诺，
  也就是说，在任何一个行业或领域，只要做到 1 万小时的练习，几乎人人都能成为该行业或领域的专家。
  但在我的研究中，根本没有这样的迹象。
- 格拉德威尔有一个观点是对的，值得在这里重复一遍，因为它至关重要：在任何一个有着悠久历史的行业或领域，
  要想成就一番事业，致力于变成业内的杰出人物，需要付出许多年艰苦卓绝的努力。
  也许并不需要恰好1万小时的练习，但要花很长时间练习。
** 第 5 章　在工作中运用刻意练习原则
#+BEGIN_QUOTE
  培养以练习为导向的心态，即不再认为工作日只能用来工作，练习只能在特殊
  时刻、特定场合才能进行，而是将日常商业活动转变成练习活动，将练习变为
  日常工作的一部分。
#+END_QUOTE
*** 王牌训练计划 (top gun school)
后来，美国空军也注意到了海军“王牌飞行员”训练的这种惊人效果，开设了一些
训练课程，目的是使空军飞行员更好地做好空中战斗的准备，而且，两个军种在
越战结束之后继续进行这种训练。到第一次海湾战争时，两个军种都已经长时间
执行了他们的训练计划，使得他们的飞行员比全世界几乎所有的其他战斗军种的
飞行员更加训练有素。在第一次海湾战争持续7个月的时间里，美军飞行员在空
战中击落了33架敌方战机，只在战斗中损失1架战机，这也许是空战史上最具压
倒性的胜利。
*** 让练习变成日常工作的一部分
我的意思是，如果你想使用刻意练习的原则，可以想一些办法来辨认某个领域或
行业中的杰出人物，然后训练其他那些表现不太出色的人，并且尽可能使后者也
达到前者的水平。做到这一点，就有可能提升整个组织或整个专业的整体绩效水
平。

任何人都可以进步，但需要正确的方法。
*** 用王牌训练方法训练医生
致力于传授知识的传统方法

当你观察人们在职业领域和商业世界中如何接受训练时，会发现一种趋势：不重
视技能，过于重视知识。主要的原因是传统和方便：向一大群人介绍知识，比起
创造条件让人们可以通过练习来提升技能，要容易得多。

简单地讲，经验丰富的医生在传统手术中学到的更多知识或者积累的更丰富经验，
都无法为他们提高腹腔镜手术的技能带来优势。这种技能必须通过独立操作来培
养。由于这些研究成果，当今那些想做腹腔镜手术的医生们，必须通过由专家级
的腹腔镜外科医生监管训练以及这项特定技能的测试，才能正式走上手术台。

可以获得反馈，最有可能是外科医生随着经验的日渐丰富而手法精进的原因，这
也是他们不同于许多其他医学专业人士的地方。

采用基于刻意练习的方法来精进技能，可能是格外宝贵的，因为从这项研究和其
他类似研究中，我们清楚地发现，外科医生需要花多年的时间、做大量的手术，
才能达到被人们认为是专家的水平。
** TODO 第 6 章　在生活中运用刻意练习原则
刻意训练针对的是每个有梦想的人，可以帮助每个想学习怎样画画、编程、变魔术、吹萨克斯管、写小说的人。它针对的是所有那些想掌控自己的人生、不甘心于现状的人们。
首先，找位好导师 //185
专注和投入至关重要 //189
没有导师，怎么办 //194
跨越停滞阶段 //201
保持动机 //206
** 第 7 章　成为杰出人物的路线图
杰出人物拥有相同的成长路线：一，产生兴趣；二，变得认真；三，全力投入；四，开拓创新。
三位女性象棋大师 //225
第一阶段：产生兴趣 //228
第二阶段：变得认真 //234
第三阶段：全力投入 //238
年龄与适应能力的关系 //240
成年人也可培养出完美音高 //246
第四阶段：开拓创新 //250
** 第 8 章　怎样解释天生才华
自闭症奇才并不是天生拥有某种神奇的才能。相反，他们和其他任何人一样，是通过练习来练就那些本领的。
破解 “帕格尼尼奇迹” //256
破解 “莫扎特传奇” //260
破解 “天才跳高运动员的神迹” //265
破解 “自闭症奇才” //270
“缺乏” 天生才华的人 //273
训练 VS“天才” //277
换个角度看基因差异 //286
相信天生才华的危险性 //292
** 第 9 章　用刻意练习创造全新的世界
我们可以给孩子留下的最重要的礼物，是帮助他们发展出本来认为自己不可能具备的能力，从而发现自己能够掌控自身潜能，也知道要使自己的梦想成真，需要用什么方法、付出怎样的努力。
用刻意练习原则教物理 //300
刻意练习的前景 //304
创造全新的世界 //313
参考文献和注释
